mywebsite_members/urls.py
# -*- coding: utf-8 -*-
"""
--------------------------------------------------------------
  Copyright (C) 2018 dsoft-app-dev.de and friends.

  This Program may be used by anyone in accordance with the terms of the
  German Free Software License

  The License may be obtained under http://www.d-fsl.org.
--------------------------------------------------------------
"""

from django.conf import settings
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import permission_required
from django.urls import include, path, re_path, reverse_lazy
from django.views.generic.base import TemplateView

from . import views

if settings.REGISTRATION_USE_ADMIN_APPROVAL:
    from registration.backends.admin_approval import views as registration_views
else:
    from registration.backends.default import views as registration_views


app_name = 'members'

urlpatterns = [
    # customized urls from registration.backends.default.urls
    path('activate/resend/', registration_views.ResendActivationView.as_view(), name='registration_resend_activation'),
    path('activate/complete/', TemplateView.as_view(template_name='registration/activation_complete.html',),
         name='registration_activation_complete'),
    # Activation keys get matched by \w+ instead of the more specific
    # [a-fA-F0-9]{40} because a bad activation key should still get to the view;
    # that way it can return a sensible "invalid key" message instead of a
    # confusing 404.
    re_path(r'^activate/(?P<activation_key>\w+)/$', views.ActivationView.as_view(), name='registration_activate'),
    path('approve/complete/', TemplateView.as_view(template_name='registration/admin_approve_complete.html'),
         name='registration_approve_complete'),
    re_path(r'^approve/(?P<profile_id>[0-9]+)/$', permission_required('is_superuser')(views.ApprovalView.as_view()),
        name='registration_admin_approve'),
    path('register/complete/', TemplateView.as_view(template_name='registration/registration_complete.html'),
         name='registration_complete'),
    path('register/closed/', TemplateView.as_view(template_name='registration/registration_closed.html'),
         name='registration_disallowed'),
    path('register/', registration_views.RegistrationView.as_view(
        disallowed_url=reverse_lazy('members:registration_disallowed'),
        success_url=reverse_lazy('members:registration_complete')),
        name='registration_register'),
    # path('register/', views.register, name='register'),
    path('profile/', views.profile, name='profile'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),
    path('profile/password/', views.change_password, name='change_password'),
    path('profile/otp/', views.change_otp, name='change_otp'),
    # customized urls from registration.auth_urls
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='registration/logout.html'), name='logout'),
    path('password/change/', auth_views.PasswordChangeView.as_view(
        success_url=reverse_lazy('members:password_change_done')),
        name='password_change'),
    path('password/change/done/', auth_views.PasswordChangeDoneView.as_view(),
         name='password_change_done'),
    path('password/reset/', auth_views.PasswordResetView.as_view(
        success_url=reverse_lazy('members:password_reset_done')),
        name='password_reset'),
    path('password/reset/complete/', auth_views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
    path('password/reset/done/', auth_views.PasswordResetDoneView.as_view(),
         name='password_reset_done'),
    re_path(r'^password/reset/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$',
            auth_views.PasswordResetConfirmView.as_view(
                success_url=reverse_lazy('members:password_reset_complete')),
            name='password_reset_confirm'),
]

test_website/urls.py
# -*- coding: utf-8 -*-
"""
--------------------------------------------------------------
  Copyright (C) 2018 dsoft-app-dev.de and friends.

  This Program may be used by anyone in accordance with the terms of the
  German Free Software License

  The License may be obtained under http://www.d-fsl.org.
--------------------------------------------------------------

Website URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""

import os

from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.db.utils import OperationalError
from django.urls import include, path, re_path
from django.views.generic import RedirectView
from django.views.i18n import JavaScriptCatalog

import menu
from filebrowser.sites import site
from mywebsite.admin import admin
from mywebsite_home import views as homeviews

urlpatterns = [
    re_path(r'^favicon\.ico$', RedirectView.as_view(url='/static/mywebsite/img/default/favicon.gif')),
    path('jet/', include('jet.urls', 'jet')),  # Django JET URLS
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),  # Django JET dashboard URLS
    path('qr/', include("django_otp.urls")),  # enable QRcode for 2FA
    path('hitcount/', include('hitcount.urls', namespace='hitcount')),  # for hitcounts built-in AJAX post view
    path('captcha/', include('captcha.urls')),  # for captcha URLS
]

# handle language prefix in URL patterns
try:
    urlpatterns += i18n_patterns(
        path('tinymce/', include('tinymce.urls')),
        path('admin/filebrowser/', site.urls),
        # added custom view, see http://www.beardygeek.com/2010/03/adding-views-to-the-django-admin/
        path('admin/manual/', homeviews.manual, name="admin-manual"),
        path('admin/doc/', include('django.contrib.admindocs.urls')),
        path('admin/', admin.site.urls),
        # added javascript translation support, see
        # https://docs.djangoproject.com/en/dev/topics/i18n/translation/#internationalization-in-javascript-code
        path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
        # added website modules
        path('', include('mywebsite_home.urls', namespace='home')),
        path('blog/', include('mywebsite_blog.urls', namespace='blog')),
        path('members/', include('mywebsite_members.urls', namespace='members')),
        prefix_default_language=False
    )
except OperationalError:
    # happens when db doesn't exist yet, views.py should be importable without this side effect
    pass

# serve media files during development
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=os.path.join(settings.BASE_DIR, 'static'))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


@classmethod
def load_menus(c):
    """
    load_menus loads the menu.py file from test_website.
    """

    # we don't need to do this more than once
    if c.loaded:
        return

    try:
        __import__('test_website.menus', fromlist=["menu", ])
    except ImportError:
        pass

    c.loaded = True


# override menu.Menu.load_menus with our own method, to load custom_website.menus instead
menu.Menu.load_menus = load_menus

mywebsite_members/models.py
# -*- coding: utf-8 -*-
"""
--------------------------------------------------------------
  Copyright (C) 2018 dsoft-app-dev.de and friends.

  This Program may be used by anyone in accordance with the terms of the
  German Free Software License

  The License may be obtained under http://www.d-fsl.org.
--------------------------------------------------------------
"""

import uuid

from django.contrib.auth import get_user_model
from django.db import models
from django.utils.timezone import now
from django.utils.translation import gettext_lazy as _
from django_otp.models import OTPSecrets
from phonenumber_field.modelfields import PhoneNumberField

# User model alias
User = get_user_model()


# Define states for PREFERRED_CONTACT_CHOICES
PREFERRED_CONTACT_CHOICES = (
    ('m', _('mobile')),
    ('p', _('phone')),
    ('e', _('email'))
)


class Profile(models.Model):
    nr = models.CharField(
        max_length=25,
        blank=True,
        null=True,
        unique=True,
        verbose_name=_('profile_nr_field')
    )
    user = models.OneToOneField(
        User,
        related_name='profile',
        on_delete=models.CASCADE,
        verbose_name=_('user_field')
    )
    title = models.CharField(
        max_length=25,
        blank=True,
        null=True,
        verbose_name=_('profile_title_field')
    )
    uuid = models.UUIDField(
        default=uuid.uuid4,
        editable=False,
        verbose_name=_('uuid_field')
    )
    company_name = models.CharField(
        max_length=250,
        verbose_name=_('company_name_field'),
        blank=True,
        null=True,
    )
    title = models.CharField(
        max_length=25,
        blank=True,
        null=True,
        verbose_name=_('profile_title_field')
    )
    website = models.CharField(
        max_length=250,
        blank=True,
        null=True,
        verbose_name=_('website_field')
    )
    mobile = PhoneNumberField(
        blank=True,
        null=True,
        verbose_name=_('mobile_field')
    )
    phone = PhoneNumberField(
        blank=True,
        null=True,
        verbose_name=_('phone_field')
    )
    fax = PhoneNumberField(
        blank=True,
        null=True,
        verbose_name=_('fax_field')
    )
    preferred_contact = models.CharField(
        max_length=6,
        choices=PREFERRED_CONTACT_CHOICES,
        blank=True,
        null=True,
        verbose_name=_('preffered_contact_field')
    )
    country = models.CharField(
        max_length=128,
        blank=True,
        null=True,
        verbose_name=_('country_field')
    )
    zipcode = models.CharField(
        max_length=10,
        blank=True,
        null=True,
        verbose_name=_('zipcode_field')
    )
    location = models.CharField(
        max_length=250,
        blank=True,
        null=True,
        verbose_name=_('location_field')
    )
    address = models.CharField(
        max_length=250,
        blank=True,
        null=True,
        verbose_name=_('address_field')
    )

    class Meta:
        db_table = 'members_profile'
        ordering = ['user']
        verbose_name = _('Profile')
        verbose_name_plural = _('Profiles')

    def __str__(self):  # __unicode__ for Python 2
        return self.user.username

mywebsite_members/views.py
# -*- coding: utf-8 -*-
"""
--------------------------------------------------------------
  Copyright (C) 2018 dsoft-app-dev.de and friends.

  This Program may be used by anyone in accordance with the terms of the
  German Free Software License

  The License may be obtained under http://www.d-fsl.org.
--------------------------------------------------------------
"""

from django import forms
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import (authenticate, get_user_model, login,
                                 update_session_auth_hash)
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordChangeForm
from django.db import transaction
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django_otp.models import OTPSecrets
from pyotp import TOTP
from registration.backends.admin_approval import views as approval_views

from .forms import (AuthenticationForm, OTPGenerationForm, ProfileForm,
                    UserForm, UserRegistrationForm)

if settings.REGISTRATION_USE_ADMIN_APPROVAL:
    from registration.backends.admin_approval import views as registration_views
else:
    from registration.backends.default import views as registration_views


# User model alias
User = get_user_model()


# def register(request):
#     if request.method == 'POST':
#         form = UserRegistrationForm(request.POST)

#         if form.is_valid():
#             userObj = form.cleaned_data
#             username = userObj['username']
#             password = userObj['password1']
#             form.save()
#             # login user
#             user = authenticate(username=username, password=password)
#             login(request, user)
#             return redirect('members:profile')
#         elif form.has_error('url', code='spam-protection') or form.has_error('message', code='spam-protection'):
#             # Fake successful creation
#             return redirect('members:profile')
#         else:
#             messages.error(request, _('Please correct the error below.'))
#     else:
#         form = UserRegistrationForm()

#     return render(request, 'members/register.html', {'form': form})


@login_required(login_url='/members/login/')
def profile(request):
    user = request.user
    profile = request.user.profile
    args = {
        'user': user,
        'profile': profile,
    }
    if hasattr(request.user, 'otp_secret'):
        args.update({'otp_enabled': 'otp_is_enabled'})
    else:
        args.update({'otp_enabled': 'otp_is_disabled'})

    return render(request, 'members/profile.html', args)


@login_required(login_url='/members/login/')
@transaction.atomic
def edit_profile(request):
    if request.method == 'POST':
        form = UserForm(request.POST, instance=request.user)
        profile_form = ProfileForm(request.POST, instance=request.user.profile)

        if form.is_valid() and profile_form.is_valid():
            form.save()
            profile_form.save()
            return redirect('members:profile')
        else:
            messages.error(request, _('Please correct the error below.'))

    else:
        form = UserForm(instance=request.user)
        profile_form = ProfileForm(instance=request.user.profile)

    args = {
        'form': form,
        'profile_form': profile_form
    }
    return render(request, 'members/edit_profile.html', args)


@login_required(login_url='/members/login/')
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST, user=request.user)

        if form.is_valid():
            form.save()
            # leave user logged in, after changing password
            update_session_auth_hash(request, form.user)
            return redirect('members:profile')
        else:
            messages.error(request, _('Please correct the error below.'))

    else:
        form = PasswordChangeForm(user=request.user)

    args = {'form': form}
    return render(request, 'members/change_password.html', args)


@login_required(login_url='/members/login/')
def change_otp(request):
    if request.method == 'POST':
        form = OTPGenerationForm(data=request.POST, instance=request.user.otp_secret)

        if "cancel" in request.POST:
            otp_secret = OTPSecrets.objects.get(user_id=request.user)
            # delete unsaved otp_secret
            if otp_secret.secret == '':
                OTPSecrets.objects.get(user_id=request.user).delete()
            return redirect('members:edit_profile')

        if "delete" in request.POST:
            OTPSecrets.objects.get(user_id=request.user).delete()
            return redirect('members:edit_profile')

        if form.is_valid():
            otp_secret = form.cleaned_data['secret']
            otp_auth = form.cleaned_data['otp_auth']
            if otp_auth != '':
                totp = TOTP(otp_secret)

                if totp.verify(otp_auth):
                    form.save()
                    return redirect('members:edit_profile')
                else:
                    messages.error(request, _('Please provide the correct 2 FA Code.'))
            else:
                messages.error(request, _('Please provide a 2 FA Code.'))

        else:
            messages.error(request, _('Please correct the error below.'))

    else:
        # create new otp, if it doesn't exist
        if not hasattr(request.user, 'otp_secret'):
            OTPSecrets.objects.create(user=request.user)

        form = OTPGenerationForm(instance=request.user.otp_secret)

    args = {'form': form}
    return render(request, 'members/change_otp.html', args)


class LoginView(auth_views.LoginView):
    form_class = AuthenticationForm
    template_name = 'django_otp/member_login.html'


class ActivationView(registration_views.ActivationView):
    """Override success_url from ActivationView of registration.backends views"""

    def get_success_url(self, user):
        return ('members:registration_activation_complete', (), {})


class ApprovalView(approval_views.ApprovalView):
    """Override success_url from ApprovalView of registration.backends.admin_approval.views"""

    def get_success_url(self, user):
        return ('members:registration_activation_complete', (), {})

mywebsite_members/templates/members/change_otp.html
{% extends 'home/base.html' %}
{% comment %}
Copyright (C) 2018 dsoft-app-dev.de and friends.

This Program may be used by anyone in accordance with the terms of the
German Free Software License

The License may be obtained under http://www.d-fsl.org.
{% endcomment %}


{% load i18n static crispy_forms_tags %}

{% block extrastyle %}
<style>
    .invalid-feedback {
        display: inline-block;
    }

</style>
{% endblock %}

{% block content %}
<section id="content">
    <div class="members">
        <h3>{% trans "CHG_OTP_HEADING" %}</h3>
        <div class="separator"></div>
        {% if messages %}
        <ul>
            {% for message in messages %}
            <li
                class="{% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}form_errors{% else %}form_messages{% endif %}">
                {{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
        <form role="form" class="form-validate well" action="" method="post" novalidate>
            {% csrf_token %} {{ form|crispy }}
            <button type="submit" class="btn btn-dark">{% trans "CHG_OTP_SUBMIT" %}</button>
            <button type="submit" class="btn btn-secondary" name="cancel">{% trans "CHG_OTP_CANCEL" %}</button>
            <button type="submit" class="btn btn-danger" name="delete">{% trans "CHG_OTP_DELETE" %}</button>
        </form>
    </div>
</section>
{% endblock %}

mywebsite_members/templates/members/password_reset_complete.html
{% extends 'home/base.html' %}
{% comment %}
Copyright (C) 2018 dsoft-app-dev.de and friends.

This Program may be used by anyone in accordance with the terms of the
German Free Software License

The License may be obtained under http://www.d-fsl.org.
{% endcomment %}


{% load i18n static %}

{% block content %}
<section id="content">
    <div class="members">
        <h3>{% trans "RST_COMPLETE_PASSWD_HEADING" %}</h3>
        <div class="separator"></div>
        <p>
            {% url 'members:login' as the_url %}
            {% blocktrans %}
            Your password has been set. You may go ahead and
            <a href="{{ the_url }}">login</a>now.
            {% endblocktrans %}
        </p>
    </div>
</section>
{% endblock %}

mywebsite_members/templates/members/password_reset_email.html
{% autoescape off %}
Um den Prozess zum Zurücksetzen des Kennworts für deinen dsoft-app-dev Account "{{user.get_username}}" zu initiieren,
klicke auf den folgenden Link:

https://{{ domain }}{% url 'members:password_reset_confirm' uidb64=uid token=token %}

Wenn der obige Link nicht funktioniert, kopiere die URL und füge sie stattdessen in einem neuen Browser-Fenster ein.

Mit freundlichen Grüßen
Chris (dsoft-app-dev.de)


---------------------------------------------------------------------

English version:

To initiate the password reset process for your dsoft-app-dev account "{{ user.get_username }}",
click the link below:

https://{{ domain }}{% url 'members:password_reset_confirm' uidb64=uid token=token %}

If clicking the link above doesn't work, please copy and paste the URL in a new browser
window instead.

Best regards,
Chris (dsoft-app-dev.de)
{% endautoescape %}

mywebsite_members/templates/members/profile.html
{% extends 'home/base.html' %}
{% comment %}
Copyright (C) 2018 dsoft-app-dev.de and friends.

This Program may be used by anyone in accordance with the terms of the
German Free Software License

The License may be obtained under http://www.d-fsl.org.
{% endcomment %}


{% load i18n static %}

{% block content %}
<section id="content">
    <div class="members">
        <h3>{% trans "PROFILE_HEADING" %}</h3>
        <div class="separator"></div>
        <!-- Nav tabs -->
        <ul class="nav nav-tabs" role="tablist">
            <li class="nav-item">
                <a class="nav-link active" data-toggle="tab" href="#account" role="tab">{% trans "Account" %}</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#security" role="tab">{% trans "Security" %}</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'members:logout' %}">{% trans "Log out" %}</a>
            </li>
        </ul>
        <!-- Tab panes -->
        <div class="tab-content">
            <div class="tab-pane active" id="account" role="tabpanel">
                <div class="separator"></div>
                <p>
                    <div class="row">
                        <div class="col-xs-6 col-sm-3 col-md-2 left-label">
                            <strong>{% trans "Title" %}:</strong>
                        </div>
                        <div class="col-xs-6 col-sm-3 col-md-4">
                            {% if profile.title %}
                            {{ profile.title }}
                            {% else %}
                            {% trans "None" %}
                            {% endif %}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-6 col-sm-3 col-md-2 left-label">
                            <strong>{% trans "First name" %}:</strong>
                        </div>
                        <div class="col-xs-6 col-sm-3 col-md-4">
                            {% if user.first_name %}
                            {{ user.first_name }}
                            {% else %}
                            {% trans "None" %}
                            {% endif %}
                        </div>
                        <div class="col-xs-6 col-sm-3 col-md-2 left-label">
                            <strong>{% trans "Last name" %}:</strong>
                        </div>
                        <div class="col-xs-6 col-sm-3 col-md-4">
                            {% if user.last_name %}
                            {{ user.last_name }}
                            {% else %}
                            {% trans "None" %}
                            {% endif %}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-6 col-xs-offset-0 col-sm-3 col-md-2 left-label">
                            <strong>{% trans "Username" %}:</strong>
                        </div>
                        <div class="col-xs-6 col-sm-3 col-md-4">
                            {{ user }}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-6 col-sm-3 col-md-2 left-label">
                            <strong>{% trans "company_name_field" %}:</strong>
                        </div>
                        <div class="col-xs-6 col-sm-3 col-md-4">
                            {% if profile.company_name %}
                            {{ profile.company_name }}
                            {% else %}
                            {% trans "None" %}
                            {% endif %}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-6 col-sm-3 col-md-2 left-label">
                            <strong>{% trans "address_field" %}:</strong>
                        </div>
                        <div class="col-xs-6 col-sm-3 col-md-4">
                            {% if profile.address %}
                            {{ profile.address }}
                            {% else %}
                            {% trans "None" %}
                            {% endif %}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-6 col-sm-3 col-md-2 left-label">
                            <strong>{% trans "zipcode_field" %}:</strong>
                        </div>
                        <div class="col-xs-6 col-sm-3 col-md-4">
                            {% if profile.zipcode %}
                            {{ profile.zipcode }}
                            {% else %}
                            {% trans "None" %}
                            {% endif %}
                        </div>
                        <div class="col-xs-6 col-sm-3 col-md-2 left-label">
                            <strong>{% trans "location_field" %}:</strong>
                        </div>
                        <div class="col-xs-6 col-sm-3 col-md-4">
                            {% if profile.location %}
                            {{ profile.location }}
                            {% else %}
                            {% trans "None" %}
                            {% endif %}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-6 col-sm-3 col-md-2 left-label">
                            <strong>{% trans "email_field" %}:</strong>
                        </div>
                        <div class="col-xs-6 col-sm-3 col-md-4">
                            {% if user.email %}
                            {{ user.email }}
                            {% else %}
                            {% trans "None" %}
                            {% endif %}
                        </div>
                        <div class="col-xs-6 col-sm-3 col-md-2 left-label">
                            <strong>{% trans "website_field" %}:</strong>
                        </div>
                        <div class="col-xs-6 col-sm-3 col-md-4">
                            {% if profile.website %}
                            {{ profile.website }}
                            {% else %}
                            {% trans "None" %}
                            {% endif %}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-6 col-sm-3 col-md-2 left-label">
                            <strong>{% trans "mobile_field" %}:</strong>
                        </div>
                        <div class="col-xs-6 col-sm-3 col-md-4">
                            {% if profile.mobile %}
                            {{ profile.mobile.as_international }}
                            {% else %}
                            {% trans "None" %}
                            {% endif %}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-6 col-sm-3 col-md-2 left-label">
                            <strong>{% trans "phone_field" %}:</strong>
                        </div>
                        <div class="col-xs-6 col-sm-3 col-md-4">
                            {% if profile.phone %}
                            {{ profile.phone.as_international }}
                            {% else %}
                            {% trans "None" %}
                            {% endif %}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-6 col-sm-3 col-md-2 left-label">
                            <strong>{% trans "fax_field" %}:</strong>
                        </div>
                        <div class="col-xs-6 col-sm-3 col-md-4">
                            {% if profile.fax %}
                            {{ profile.fax.as_international }}
                            {% else %}
                            {% trans "None" %}
                            {% endif %}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-6 col-sm-3 col-md-2 left-label">
                            <strong>{% trans "preffered_contact_field" %}:</strong>
                        </div>
                        <div class="col-xs-6 col-sm-3 col-md-4">
                            {% if profile.get_preferred_contact_display %}
                            {{ profile.get_preferred_contact_display }}
                            {% else %}
                            {% trans "None" %}
                            {% endif %}
                        </div>
                    </div>
                </p>
                <div class="separator"></div>
                <a href="{% url 'members:edit_profile' %}" class="btn btn-dark">{% trans "PROFILE_EDIT" %}</a>
            </div>
            <div class="tab-pane" id="security" role="tabpanel">
                <div class="separator"></div>
                <p>
                    <div class="row">
                        <div class="col-xs-6 col-sm-3 col-md-2 left-label">
                            <strong>{% trans "Password" %}:</strong>
                        </div>
                        <div class="col-xs-6 col-sm-9 col-md-10">
                            {% url 'members:change_password' as the_url %}
                            {% blocktrans %}
                            Raw passwords are not stored, so there is no way to see this
                            user`s password, but you can change the password using
                            <a href="{{ the_url }}">this form</a>.
                            {% endblocktrans %}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-6 col-sm-3 col-md-2 left-label">
                            <strong>{% trans "2 FA Code" %}:</strong>
                        </div>
                        <div class="col-xs-6 col-sm-9 col-md-10">
                            <span class="{{ otp_enabled }}" />
                            &nbsp;
                            <a href="{% url 'members:change_otp' %}">{% trans "PROFILE_CHG_OTP" %}</a>
                        </div>
                    </div>
                </p>
                <div class="separator"></div>
            </div>
        </div>
    </div>
</section>
{% endblock %}